[package]
name = "FMData"
version = "0.1.0"
authors = ["Bjoern Doebel <bjoern.doebel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "fm_google_up"
path = "src/bin/player_uploader.rs"

[dependencies]
clap = "3.0.0-beta.2"

table-extract = "0.2.2"
tokio = { version = "1", features = ["full"] }

serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
yup-oauth2 = "^11.0"

sheets = "0.7.0"