[package]
name = "FMData"
version = "0.1.0"
authors = ["Bjoern Doebel <bjoern.doebel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "player_uploader"
path = "src/bin/player_uploader.rs"

[lib]
name = "fm_google_api"
path = "src/lib/fm_google_api.rs"

#[[bin]]
#name = "min_ex"
#path  = "src/bin/minimal.rs"

[dependencies]
clap = "3.0.0-beta.2"

google-sheets4 = "*"
google-drive3 = "*"
# This project intentionally uses an old version of Hyper. See
# https://github.com/Byron/google-apis-rs/issues/173 for more
# information.
hyper = "^0.10"
hyper-rustls = "^0.6"

table-extract = "0.2.2"
serde = "^1.0"
serde_json = "^1.0"
yup-oauth2 = "^1.0"
